/**
 * @file models/plantModel.js
 * @description Handles all database interactions for the plants_in_beds resource and the plants catalog.
 */

//Imports
const { pool } = require('../db');

/**
 * Saves an entire array of plants to a bed in a single transaction.
 * @param {string} userId - The ID of the user.
 * @param {string} gardenId - The ID of the garden.
 * @param {string} bedId - The ID of the bed.
 * @param {Array<Object>} plantsArray - An array of plant objects to save.
 * @returns {Promise<void>} A promise that resolves when the operation is complete.
 */
async function savePlantsInBed(userId, gardenId, bedId, plantsArray) {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        // Step 1: Validate the bed exists and belongs to the user
        const bedCheckQuery = `
            SELECT gb.id FROM garden_beds gb
            JOIN gardens g ON gb.garden_id = g.id
            WHERE g.user_id = $1 AND g.id = $2 AND gb.id = $3;
        `;
        const { rows: bedRows } = await client.query(bedCheckQuery, [userId, gardenId, bedId]);
        if (bedRows.length === 0) {
            throw new Error('Validation error: Bed does not exist or does not belong to the user/garden.');
        }

        // Step 2: Delete all existing plants for the bed
        const deleteQuery = 'DELETE FROM plants_in_beds WHERE bed_id = $1;';
        await client.query(deleteQuery, [bedId]);

        // Step 3: Insert all new plants from the array
       const insertQuery = `
    INSERT INTO plants_in_beds (id, bed_id, plant_id, planted_date, x_position, y_position, plant_role, icon, spacing, name)
    VALUES ($1, $2, $3, NOW(), $4, $5, $6, $7, $8, $9);
`;
    for (const plant of plantsArray) {
            await client.query(insertQuery, [
    plant.id,       // $1
    bedId,          // $2
    plant.plant_id, // $3
    // The planted_date is automatically generated by NOW() in the query
    plant.x_position, // $4
    plant.y_position, // $5
    plant.plant_role, // $6
    plant.icon,       // $7
    plant.spacing,    // $8
    plant.name        // $9 - This is the new field
]);
        }

        await client.query('COMMIT');
    } catch (error) {
        await client.query('ROLLBACK');
        console.error('Transaction error in plantModel.savePlantsInBed:', error);
        throw error;
    } finally {
        client.release();
    }
}

/**
 * Gets all plants for a specific bed, but only returns elements directly from the plants_in_beds table.
 * @param {string} userId - The ID of the user.
 * @param {string} gardenId - The ID of the garden.
 * @param {string} bedId - The ID of the bed.
 * @returns {Promise<Array<Object>>} An array of plant objects.
 */
async function getPlantsForBed(userId, gardenId, bedId) {
    try {
        // The query is now simplified to only select columns from plants_in_beds.
        const plantQuery = `
            SELECT
                id,
                bed_id,
                plant_id,
                planted_date,
                x_position,
                y_position,
                plant_role,
                icon,
                spacing,
                name
            FROM plants_in_beds
            WHERE bed_id = $1;
        `;
        // Corrected: Only pass the bedId to the query
        const { rows } = await pool.query(plantQuery, [bedId]);
        return rows;
    } catch (error) {
        console.error('Database error in plantModel.getPlantsForBed:', error);
        throw error;
    }
}

/**
 * Gets all plants from the catalog.
 * @returns {Promise<Array<Object>>} An array of plant objects.
 */
async function getAllPlants() {
    try {
        const plantQuery = 'SELECT * FROM plants;';
        const { rows } = await pool.query(plantQuery);
        return rows;
    } catch (error) {
        console.error('Database error in plantModel.getAllPlants:', error);
        throw error;
    }
}

/**
 * Gets a single plant from the catalog by its ID.
 * @param {string} plantId - The ID of the plant.
 * @returns {Promise<Object|null>} The plant object or null if not found.
 */
async function getPlantById(plantId) {
    try {
        const plantQuery = 'SELECT * FROM plants WHERE id = $1;';
        const { rows } = await pool.query(plantQuery, [plantId]);
        return rows[0] || null;
    } catch (error) {
        console.error('Database error in plantModel.getPlantById:', error);
        throw error;
    }
}

/**
 * Deletes all plant-to-bed associations for a given bed ID.
 * @param {number} bedId - The ID of the bed.
 * @returns {Promise<number>} The number of deleted associations.
 */
async function removeByBedId(bedId) {
    try {
        const query = 'DELETE FROM plants_in_beds WHERE bed_id = $1 RETURNING id;';
        const { rowCount } = await pool.query(query, [bedId]);
        return rowCount;
    } catch (error) {
        console.error('Database error in plantModel.removeByBedId:', error);
        throw error;
    }
}


module.exports = {
    savePlantsInBed,
    getPlantsForBed,
    getAllPlants,
    getPlantById,
    removeByBedId
};
